### ISSUE TITLE
Nothing to sync, there are no hosts with subscription for this organization.

### ISSUE THREAD

**Issue by nixfu** [theforeman/foreman_rh_cloud#879]
I am trying to setup rh_cloud with Foreman 3.10/Katello 4.12 and foreman_rh_cloud 9.0.55/rubygem-foreman_rh_cloud-9.0.55-2.

I registered a client, and their inventory data from Foreman seems to be uploading to console.redhat.com ok, and I see the info for that host and a recommendation from insight.

However, I am unable to download the recommendations for the host to Foreman.  

Whenever I click the "Sync Inventroy Status", I get the error message: 

> Inventory sync has failed: ERF74-6085 [InventoryUpload::TaskActions::NothingToSyncError]: Nothing to sync, there are no hosts with subscription for this organization.

This Foreman environment, is setup in Simple Access Mode so technically no host have been assigned a subscription.

I have set a global parameter host_registration_insights = true.

Is there a dependency on not using Simple Content Access for rh_cloud to work?

As of Foreman 4.12, Simple Content Access is mandatory I believe.

**Comment by nixfu** [comment]
FYI, was resolved by insights-client --unregister, then insights-client --register of my test host.  Now its working.

**Comment by nixfu** [comment]
Resolved

**Comment by chris1984** [comment]
Glad you got it fixed, sorry for the delay in looking at this
